version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile:  Dockerfile.postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123456
      POSTGRES_DB: TestAPI

  fastapi:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres